/** Section headers for Browse's gojuon-row grouping -- matches the `gojuon_row` values seeded
 * onto the hiragana/katakana reference tables (see 20260822_kana_tables.sql). */
export const GOJUON_ROW_LABELS: Record<string, string> = {
  a: "A",
  ka: "KA",
  sa: "SA",
  ta: "TA",
  na: "NA",
  ha: "HA",
  ma: "MA",
  ya: "YA",
  ra: "RA",
  wa: "WA",
  n: "N",
  ga: "GA",
  za: "ZA",
  da: "DA",
  ba: "BA",
  pa: "PA",
  kya: "KYA",
  sha: "SHA",
  cha: "CHA",
  nya: "NYA",
  hya: "HYA",
  mya: "MYA",
  rya: "RYA",
  gya: "GYA",
  ja: "JA",
  bya: "BYA",
  pya: "PYA",
};

/** Row order + character count per gojuon row, identical for hiragana and katakana (same 104
 * characters, same grouping, just a different script) -- see 20260822_kana_tables.sql. The kana
 * syllabaries are a closed, centuries-old set that will never gain or lose a row, so Browse's
 * loading skeleton can mirror this exact shape instead of a generic/arbitrary placeholder grid. */
export const GOJUON_ROW_LAYOUT: readonly { row: string; count: number }[] = [
  { row: "a", count: 5 },
  { row: "ka", count: 5 },
  { row: "sa", count: 5 },
  { row: "ta", count: 5 },
  { row: "na", count: 5 },
  { row: "ha", count: 5 },
  { row: "ma", count: 5 },
  { row: "ya", count: 3 },
  { row: "ra", count: 5 },
  { row: "wa", count: 2 },
  { row: "n", count: 1 },
  { row: "ga", count: 5 },
  { row: "za", count: 5 },
  { row: "da", count: 5 },
  { row: "ba", count: 5 },
  { row: "pa", count: 5 },
  { row: "kya", count: 3 },
  { row: "sha", count: 3 },
  { row: "cha", count: 3 },
  { row: "nya", count: 3 },
  { row: "hya", count: 3 },
  { row: "mya", count: 3 },
  { row: "rya", count: 3 },
  { row: "gya", count: 3 },
  { row: "ja", count: 3 },
  { row: "bya", count: 3 },
  { row: "pya", count: 3 },
];
