/** Section headers for Browse's gojuon-row grouping -- matches the `gojuon_row` values seeded
 * onto the hiragana/katakana reference tables (see 20260822_kana_tables.sql). */
export const GOJUON_ROW_LABELS: Record<string, string> = {
  a: "A",
  ka: "KA",
  sa: "SA",
  ta: "TA",
  na: "NA",
  ha: "HA",
  ma: "MA",
  ya: "YA",
  ra: "RA",
  wa: "WA",
  n: "N",
  ga: "GA",
  za: "ZA",
  da: "DA",
  ba: "BA",
  pa: "PA",
  kya: "KYA",
  sha: "SHA",
  cha: "CHA",
  nya: "NYA",
  hya: "HYA",
  mya: "MYA",
  rya: "RYA",
  gya: "GYA",
  ja: "JA",
  bya: "BYA",
  pya: "PYA",
};
