-- Run this manually in DBeaver or the Supabase SQL editor.
--
-- Rewrites public.test's identity column to a clean, contiguous 1..204 range instead of the
-- 172..375 gap left behind by the delete+reinsert cycles in 20261101/20261102/20261103 (each
-- cycle never restarts the sequence -- see the "not restarting the id identity this time" note in
-- 20261101 -- so it just keeps climbing). Confirmed live on 2026-09-12: the only FK pointing at
-- test(id) is user_reading_test_progress.sentence_id (on delete cascade), and it has 0 rows, so
-- there's no real progress data that a renumber could orphan or lose. This is a one-time cleanup
-- while the table is still pre-launch -- once real users have progress rows, truncating this table
-- would wipe their progress, so this isn't something to repeat later.
--
-- `truncate ... restart identity cascade` empties public.test (cascading to the already-empty
-- user_reading_test_progress) and resets the id sequence to start at 1. The insert below is the
-- union of 20261101 (hiragana) + 20261102 + 20261103 (katakana) content, re-run in the same order
-- so the new ids land in the same relative order as before: hiragana 1-78, then katakana 79-204.

truncate table public.test restart identity cascade;

insert into public.test (sort_order, question, romaji, english, test_type) values
-- hiragana (20261101_test_hiragana_words_v2.sql)
(1, 'あさ', 'asa', 'morning', 'hiragana'),
(2, 'おおきい', 'ookii', 'big', 'hiragana'),
(3, 'かぜ', 'kaze', 'wind / cold', 'hiragana'),
(4, 'ぞう', 'zou', 'elephant', 'hiragana'),
(5, 'げんき', 'genki', 'energetic / well', 'hiragana'),
(6, 'でんわ', 'denwa', 'telephone', 'hiragana'),
(7, 'こども', 'kodomo', 'child', 'hiragana'),
(8, 'ばん', 'ban', 'evening', 'hiragana'),
(9, 'かぎ', 'kagi', 'key', 'hiragana'),
(10, 'ごはん', 'gohan', '(cooked) rice / meal', 'hiragana'),
(11, 'むし', 'mushi', 'insect', 'hiragana'),
(12, 'め', 'me', 'eye', 'hiragana'),
(13, 'ほん', 'hon', 'book', 'hiragana'),
(14, 'へや', 'heya', 'room', 'hiragana'),
(15, 'ふゆ', 'fuyu', 'winter', 'hiragana'),
(16, 'これ', 'kore', 'this', 'hiragana'),
(17, 'さくら', 'sakura', 'cherry blossom', 'hiragana'),
(18, 'よる', 'yoru', 'night', 'hiragana'),
(19, 'はなぢ', 'hanaji', 'nosebleed', 'hiragana'),
(20, 'つづく', 'tsuzuku', 'to continue', 'hiragana'),
(21, 'こんな', 'konna', 'like this', 'hiragana'),
(22, 'こんにちは', 'konnichiwa', 'hello', 'hiragana'),
(23, 'ざんねん', 'zannen', 'too bad / a pity', 'hiragana'),
(24, 'かんぬし', 'kannushi', 'Shinto shrine priest', 'hiragana'),
(25, 'たんのう', 'tannou', 'to fully enjoy / proficient', 'hiragana'),
(26, 'きゃく', 'kyaku', 'customer / guest', 'hiragana'),
(27, 'きゅう', 'kyuu', 'nine', 'hiragana'),
(28, 'べんきょう', 'benkyou', 'study', 'hiragana'),
(29, 'しゃしん', 'shashin', 'photo', 'hiragana'),
(30, 'しゅくだい', 'shukudai', 'homework', 'hiragana'),
(31, 'しょくじ', 'shokuji', 'meal', 'hiragana'),
(32, 'ちゃいろ', 'chairo', 'brown', 'hiragana'),
(33, 'ちゅうい', 'chuui', 'caution / attention', 'hiragana'),
(34, 'ちょっと', 'chotto', 'a little / hold on', 'hiragana'),
(35, 'にゃんこ', 'nyanko', 'kitty', 'hiragana'),
(36, 'ぎゅうにゅう', 'gyuunyuu', 'milk', 'hiragana'),
(37, 'にょうぼう', 'nyoubou', '(one''s) wife', 'hiragana'),
(38, 'ひゃく', 'hyaku', 'hundred', 'hiragana'),
(39, 'ひゅう　ひゅう', 'hyuu hyuu', '(onomatopoeia) whistling wind', 'hiragana'),
(40, 'ひょう', 'hyou', 'hail', 'hiragana'),
(41, 'みゃく', 'myaku', 'pulse', 'hiragana'),
(42, 'みゅ', 'myu', '', 'hiragana'),
(43, 'みょうが', 'myouga', 'Japanese ginger', 'hiragana'),
(44, 'りゃく', 'ryaku', 'abbreviation', 'hiragana'),
(45, 'りゅう', 'ryuu', 'dragon', 'hiragana'),
(46, 'りょこう', 'ryokou', 'trip / travel', 'hiragana'),
(47, 'ぎゃく', 'gyaku', 'opposite', 'hiragana'),
(48, 'ぎょうざ', 'gyouza', 'dumpling', 'hiragana'),
(49, 'じゃがいも', 'jagaimo', 'potato', 'hiragana'),
(50, 'じゅぎょう', 'jugyou', 'class / lesson', 'hiragana'),
(51, 'じょうず', 'jouzu', 'skillful', 'hiragana'),
(52, 'だいじょうぶ', 'daijoubu', 'it''s okay / fine', 'hiragana'),
(53, 'びゃっこ', 'byakko', 'White Tiger (mythical beast)', 'hiragana'),
(54, 'びゅう　びゅう', 'byuu byuu', '(onomatopoeia) strong wind', 'hiragana'),
(55, 'びょういん', 'byouin', 'hospital', 'hiragana'),
(56, 'ろっぴゃく', 'roppyaku', 'six hundred', 'hiragana'),
(57, 'ぴゅう　ぴゅう', 'pyuu pyuu', '(onomatopoeia) whistling', 'hiragana'),
(58, 'ぴょん　ぴょん', 'pyon pyon', '(onomatopoeia) hopping', 'hiragana'),
(59, 'けっか', 'kekka', 'result', 'hiragana'),
(60, 'さっき', 'sakki', 'a little while ago', 'hiragana'),
(61, 'びっくり', 'bikkuri', 'surprised', 'hiragana'),
(62, 'いっけん', 'ikken', 'at first glance', 'hiragana'),
(63, 'がっこう', 'gakkou', 'school', 'hiragana'),
(64, 'いっさい', 'issai', 'entirely / (not) at all', 'hiragana'),
(65, 'ぐっすり', 'gussuri', 'soundly (sleep)', 'hiragana'),
(66, 'けっせき', 'kesseki', 'absence', 'hiragana'),
(67, 'ひっそり', 'hissori', 'quietly', 'hiragana'),
(68, 'もったいない', 'mottainai', 'wasteful', 'hiragana'),
(69, 'こっち', 'kocchi', 'this way / here', 'hiragana'),
(70, 'みっつ', 'mittsu', 'three (items)', 'hiragana'),
(71, 'まって', 'matte', 'wait!', 'hiragana'),
(72, 'いっぱい', 'ippai', 'full / a lot', 'hiragana'),
(73, 'えんぴつ', 'enpitsu', 'pencil', 'hiragana'),
(74, 'きっぷ', 'kippu', 'ticket', 'hiragana'),
(75, 'いっぴき', 'ippiki', 'one (small animal, counter)', 'hiragana'),
(76, 'いっぺん', 'ippen', 'once', 'hiragana'),
(77, 'しっぽ', 'shippo', 'tail', 'hiragana'),
(78, 'ざっし', 'zasshi', 'magazine', 'hiragana'),
-- katakana (20261102_test_katakana_words_v2.sql)
(1, 'アート', 'aato', 'art', 'katakana'),
(2, 'イースター', 'iisutaa', 'Easter', 'katakana'),
(3, 'ウール', 'uuru', 'wool', 'katakana'),
(4, 'エース', 'eesu', 'ace', 'katakana'),
(5, 'オーブン', 'oobun', 'oven', 'katakana'),
(6, 'カード', 'kaado', 'card', 'katakana'),
(7, 'スキー', 'sukii', 'ski', 'katakana'),
(8, 'クーラー', 'kuuraa', 'air conditioner', 'katakana'),
(9, 'ケーキ', 'keeki', 'cake', 'katakana'),
(10, 'コーヒー', 'koohii', 'coffee', 'katakana'),
(11, 'サービス', 'saabisu', 'service', 'katakana'),
(12, 'タクシー', 'takushii', 'taxi', 'katakana'),
(13, 'スーツ', 'suutsu', 'suit', 'katakana'),
(14, 'セーター', 'seetaa', 'sweater', 'katakana'),
(15, 'ソーセージ', 'sooseeji', 'sausage', 'katakana'),
(16, 'チーズ', 'chiizu', 'cheese', 'katakana'),
(17, 'ツール', 'tsuuru', 'tool', 'katakana'),
(18, 'テーブル', 'teeburu', 'table', 'katakana'),
(19, 'トースト', 'toosuto', 'toast', 'katakana'),
(20, 'コーナー', 'koonaa', 'corner', 'katakana'),
(21, 'ニーズ', 'niizu', 'needs / demand', 'katakana'),
(22, 'ヌードル', 'nuudoru', 'noodle', 'katakana'),
(23, 'ネーム', 'neemu', 'name', 'katakana'),
(24, 'ノート', 'nooto', 'notebook', 'katakana'),
(25, 'ハート', 'haato', 'heart', 'katakana'),
(26, 'ヘーゼルナッツ', 'heezerunattsu', 'hazelnut', 'katakana'),
(27, 'ホームページ', 'hoomupeeji', 'homepage', 'katakana'),
(28, 'ハンマー', 'hanmaa', 'hammer', 'katakana'),
(29, 'ミートボール', 'miitobooru', 'meatball', 'katakana'),
(30, 'ムード', 'muudo', 'mood', 'katakana'),
(31, 'メール', 'meeru', 'email', 'katakana'),
(32, 'モーター', 'mootaa', 'motor', 'katakana'),
(33, 'プレイヤー', 'pureiyaa', 'player', 'katakana'),
(34, 'ユーモア', 'yuumoa', 'humor', 'katakana'),
(35, 'ヨーグルト', 'yooguruto', 'yogurt', 'katakana'),
(36, 'シリーズ', 'shiriizu', 'series', 'katakana'),
(37, 'ルーム', 'ruumu', 'room', 'katakana'),
(38, 'カレー', 'karee', 'curry', 'katakana'),
(39, 'ヒーロー', 'hiiroo', 'hero', 'katakana'),
(40, 'ワード', 'waado', 'word', 'katakana'),
(41, 'ガム', 'gamu', 'gum', 'katakana'),
(42, 'ピザ', 'piza', 'pizza', 'katakana'),
(43, 'サラダ', 'sarada', 'salad', 'katakana'),
(44, 'デパート', 'depaato', 'department store', 'katakana'),
(45, 'マンゴー', 'mangoo', 'mango', 'katakana'),
(46, 'キャベツ', 'kyabetsu', 'cabbage', 'katakana'),
(47, 'キューブ', 'kyuubu', 'cube', 'katakana'),
(48, 'キョン', 'kyon', 'muntjac (deer species)', 'katakana'),
(49, 'シャワー', 'shawaa', 'shower', 'katakana'),
(50, 'シュート', 'shuuto', 'shoot (sports)', 'katakana'),
(51, 'ショップ', 'shoppu', 'shop', 'katakana'),
(52, 'チャンス', 'chansu', 'chance', 'katakana'),
(53, 'チューリップ', 'chuurippu', 'tulip', 'katakana'),
(54, 'チョコレート', 'chokoreeto', 'chocolate', 'katakana'),
(55, 'ニャー', 'nyaa', 'meow', 'katakana'),
(56, 'ニュース', 'nyuusu', 'news', 'katakana'),
(57, 'ニョッキ', 'nyokki', 'gnocchi', 'katakana'),
(58, 'ヒューズ', 'hyuuzu', 'fuse', 'katakana'),
(59, 'ミャンマー', 'myanmaa', 'Myanmar', 'katakana'),
(60, 'ミュージック', 'myuujikku', 'music', 'katakana'),
(61, 'リュックサック', 'ryukkusakku', 'rucksack / backpack', 'katakana'),
(62, 'ギャング', 'gyangu', 'gang', 'katakana'),
(63, 'レギュラー', 'regyuraa', 'regular', 'katakana'),
(64, 'ギョーザ', 'gyooza', 'dumpling', 'katakana'),
(65, 'ジャム', 'jamu', 'jam', 'katakana'),
(66, 'ジュース', 'juusu', 'juice', 'katakana'),
(67, 'ジョギング', 'jogingu', 'jogging', 'katakana'),
(68, 'インタビュー', 'intabyuu', 'interview', 'katakana'),
(69, 'コンピューター', 'konpyuutaa', 'computer', 'katakana'),
(70, 'サッカー', 'sakkaa', 'soccer', 'katakana'),
(71, 'クッキー', 'kukkii', 'cookie', 'katakana'),
(72, 'パッケージ', 'pakkeeji', 'package', 'katakana'),
(73, 'モロッコ', 'morokko', 'Morocco', 'katakana'),
(74, 'マッサージ', 'massaaji', 'massage', 'katakana'),
(75, 'ファッション', 'fasshon', 'fashion', 'katakana'),
(76, 'レッスン', 'ressun', 'lesson', 'katakana'),
(77, 'メッセージ', 'messeeji', 'message', 'katakana'),
(78, 'エスプレッソ', 'esupuresso', 'espresso', 'katakana'),
(79, 'カッター', 'kattaa', 'cutter', 'katakana'),
(80, 'サンドイッチ', 'sandoicchi', 'sandwich', 'katakana'),
(81, 'ナッツ', 'nattsu', 'nuts', 'katakana'),
(82, 'バッテリー', 'batterii', 'battery', 'katakana'),
(83, 'ロボット', 'robotto', 'robot', 'katakana'),
(84, 'ヨーロッパ', 'yooroppa', 'Europe', 'katakana'),
(85, 'ヒッピー', 'hippii', 'hippie', 'katakana'),
(86, 'ワッペン', 'wappen', 'patch / badge', 'katakana'),
(87, 'ニッポン', 'nippon', 'Japan', 'katakana'),
(88, 'バッグ', 'baggu', 'bag', 'katakana'),
(89, 'グッズ', 'guzzu', 'goods', 'katakana'),
(90, 'ベッド', 'beddo', 'bed', 'katakana'),
(91, 'バッジ', 'bajji', 'badge', 'katakana'),
(92, 'アンナ', 'anna', 'Anna (name)', 'katakana'),
(93, 'アンニュイ', 'annyui', 'languid / ennui', 'katakana'),
(94, 'アンヌ', 'annu', 'Anne (name)', 'katakana'),
(95, 'アンネ', 'anne', 'Anne (e.g. Anne Frank)', 'katakana'),
(96, 'アンノウン', 'announ', 'unknown', 'katakana'),
(97, 'ヴァイオリン', 'vaiorin', 'violin', 'katakana'),
(98, 'ヴィーガン', 'viigan', 'vegan', 'katakana'),
(99, 'ヴェール', 'veeru', 'veil', 'katakana'),
(100, 'ヴォーカル', 'vookaru', 'vocal', 'katakana'),
(101, 'シェフ', 'shefu', 'chef', 'katakana'),
(102, 'ジェットコースター', 'jettokoosutaa', 'roller coaster', 'katakana'),
(103, 'チェック', 'chekku', 'check', 'katakana'),
(104, 'パーティー', 'paatii', 'party', 'katakana'),
(105, 'キャンディ', 'kyandi', 'candy', 'katakana'),
(106, 'ヒンドゥー', 'hinduu', 'Hindu', 'katakana'),
(107, 'ファミリー', 'famirii', 'family', 'katakana'),
(108, 'フィルム', 'firumu', 'film', 'katakana'),
(109, 'カフェ', 'kafe', 'café', 'katakana'),
(110, 'フォーク', 'fooku', 'fork', 'katakana'),
(111, 'ウィンドウ', 'windou', 'window', 'katakana'),
(112, 'ウェブ', 'webu', 'web', 'katakana'),
(113, 'ウォーキング', 'wookingu', 'walking', 'katakana'),
-- katakana gap fill (20261103_test_katakana_gap_fill.sql)
(114, 'チヂミ', 'chijimi', 'chijimi (Korean pancake)', 'katakana'),
(115, 'ビャクダン', 'byakudan', 'sandalwood', 'katakana'),
(116, 'ヒョッコリ', 'hyokkori', 'suddenly / unexpectedly (onomatopoeia)', 'katakana'),
(117, 'ミョウバン', 'myouban', 'alum', 'katakana'),
(118, 'リャマ', 'ryama', 'llama', 'katakana'),
(119, 'リョウ', 'ryou', 'Ryo (name)', 'katakana'),
(120, 'ハッブル', 'habburu', 'Hubble', 'katakana'),
(121, 'ビョーキ', 'byouki', 'sick (slang)', 'katakana'),
(122, 'トゥクトゥク', 'tukutuku', 'tuk-tuk', 'katakana'),
(123, 'ヒャッホー', 'hyahhoo', 'yahoo! (exclamation of joy)', 'katakana'),
(124, 'ピャー', 'pyaa', 'eek! (surprise sound effect)', 'katakana'),
(125, 'ヴードゥー', 'vuuduu', 'voodoo', 'katakana'),
(126, 'ヅ', 'zu', '', 'katakana');

update public.test
set particle_furiganas = ARRAY[NULL, NULL, NULL, NULL, 'wa']::text[]
where test_type = 'hiragana' and sort_order = 22;
