/** Web push in the browser: asking permission, subscribing this device, and telling whether it already is. The
 * server side is worker/lib/lessonsPush.ts; the service worker that shows the notification is generated by
 * scripts/generate-sw.mjs. */

export function pushSupported(): boolean {
  return typeof window !== "undefined" && "serviceWorker" in navigator && "PushManager" in window && "Notification" in window;
}

/** iPhones and iPads only deliver web push to an app that was added to the Home Screen. */
export function needsInstallForPush(): boolean {
  if (typeof window === "undefined") return false;
  const ios = /iPad|iPhone|iPod/.test(navigator.userAgent) || (navigator.platform === "MacIntel" && navigator.maxTouchPoints > 1);
  const standalone = window.matchMedia("(display-mode: standalone)").matches || (navigator as Navigator & { standalone?: boolean }).standalone === true;
  return ios && !standalone;
}

function urlBase64ToBytes(value: string): Uint8Array<ArrayBuffer> {
  const padded = value.replace(/-/g, "+").replace(/_/g, "/").padEnd(Math.ceil(value.length / 4) * 4, "=");
  const binary = atob(padded);
  const bytes = new Uint8Array(new ArrayBuffer(binary.length));
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

/** The registration of /sw.js. The service worker only exists in a production build, so in development this
 * gives up after a few seconds instead of waiting for ever. */
async function registration(): Promise<ServiceWorkerRegistration> {
  const ready = navigator.serviceWorker.ready;
  const timeout = new Promise<never>((_, reject) => setTimeout(() => reject(new Error("no_service_worker")), 4000));
  return Promise.race([ready, timeout]);
}

export async function currentSubscription(): Promise<PushSubscription | null> {
  try {
    return await (await registration()).pushManager.getSubscription();
  } catch {
    return null;
  }
}

export interface DeviceSubscription {
  endpoint: string;
  p256dh: string;
  auth: string;
}

function toDevice(subscription: PushSubscription): DeviceSubscription {
  const json = subscription.toJSON();
  const p256dh = json.keys?.p256dh;
  const auth = json.keys?.auth;
  if (!json.endpoint || !p256dh || !auth) throw new Error("incomplete_subscription");
  return { endpoint: json.endpoint, p256dh, auth };
}

export type EnableResult = { ok: true; device: DeviceSubscription } | { ok: false; reason: "denied" | "no_service_worker" | "failed" };

/** Asks for permission (the browser shows its own prompt, so this must follow a click) and subscribes. */
export async function subscribeThisDevice(publicKey: string): Promise<EnableResult> {
  try {
    const permission = Notification.permission === "default" ? await Notification.requestPermission() : Notification.permission;
    if (permission !== "granted") return { ok: false, reason: "denied" };
    const reg = await registration();
    const existing = await reg.pushManager.getSubscription();
    // A subscription made with another server key (the keys were replaced) cannot be reused.
    const subscription = existing ?? (await reg.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: urlBase64ToBytes(publicKey) }));
    return { ok: true, device: toDevice(subscription) };
  } catch (err) {
    return { ok: false, reason: err instanceof Error && err.message === "no_service_worker" ? "no_service_worker" : "failed" };
  }
}

/** Unsubscribes this device in the browser; returns the endpoint it had, for the server to forget. */
export async function unsubscribeThisDevice(): Promise<string | null> {
  const subscription = await currentSubscription();
  if (!subscription) return null;
  const endpoint = subscription.endpoint;
  await subscription.unsubscribe().catch(() => false);
  return endpoint;
}
