$kind: http-request
url: "{{baseUrl}}/api/study-settings"
method: GET
scripts:
  - type: afterResponse
    code: |-
      pm.test('status is 401', () => pm.response.to.have.status(401));
      pm.test('has error message', () => pm.expect(pm.response.json()).to.have.property('error'));
    language: text/javascript
settings:
  disableCookies: true
order: 2000
