// Runs after `next build` (output: "export" writes the deployable site to out/). Walks the
// built output and writes out/sw.js directly -- not public/sw.js -- because the precache list
// needs the final content-hashed filenames, which only exist after the build, and public/ is
// copied into out/ *during* the build. Writing straight into out/ (wrangler.jsonc's
// assets.directory) sidesteps that chicken-and-egg problem entirely.
import { createHash } from "node:crypto";
import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const OUT_DIR = path.resolve(process.cwd(), "out");
const STATIC_ASSET_PREFIX = "_next/static/";
// Root-level files the running app actually requests (favicon, PWA icons/manifest). Excludes
// opengraph-image.png/twitter-image.png (fetched only by social-media crawlers, never by the
// app itself) and the .txt/__next.* segment-cache/diagnostic files Next 16 emits per route,
// which aren't meant to be precached blind.
const ROOT_ASSET_ALLOWLIST = new Set(["favicon.ico", "icon.svg", "apple-icon.png", "manifest.webmanifest"]);

// flag-icons ships one SVG per country/region code under flags/1x1 and flags/4x3, pulled in
// lazily via flag-icons.min.css (see useFlagIconsCss.ts) -- the browser only fetches a given
// flag once a DOM element actually uses its CSS class (CountrySelect, leaderboard). Next
// preserves each file's basename when it content-hashes them into _next/static/media, so
// reading the package's own file list gives an exact, self-updating way to recognize them and
// keep them out of the eager install-time precache below -- which would otherwise blindly
// download all ~540 of them (~3.9MB) on every visit and every deploy, regardless of whether
// anyone ever opens a country picker. They're still fetched (and cached) normally on first
// real use, via the fetch handler's _next/static/ branch.
function flagBasenames() {
  const flagsDir = path.resolve(process.cwd(), "node_modules/flag-icons/flags");
  const names = new Set();
  for (const size of ["1x1", "4x3"]) {
    for (const file of readdirSync(path.join(flagsDir, size))) names.add(file.replace(/\.svg$/, ""));
  }
  return names;
}

const FLAG_BASENAMES = flagBasenames();

function isFlagAsset(rel) {
  const base = path.basename(rel);
  if (!base.endsWith(".svg")) return false;
  const stem = base.slice(0, base.indexOf(".")); // content-hashed as `{name}.{hash}.svg`
  return FLAG_BASENAMES.has(stem);
}

function walk(dir, base = dir, files = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, base, files);
    else files.push(path.relative(base, full).split(path.sep).join("/"));
  }
  return files;
}

const allFiles = walk(OUT_DIR);
const precacheUrls = [];
const staticAssetUrls = [];

for (const rel of allFiles) {
  if (rel.startsWith(STATIC_ASSET_PREFIX)) {
    if (isFlagAsset(rel)) continue;
    const url = "/" + rel;
    precacheUrls.push(url);
    staticAssetUrls.push(url);
  } else if (rel.endsWith(".html")) {
    const route = rel === "index.html" ? "/" : "/" + rel.slice(0, -".html".length);
    precacheUrls.push(route);
  } else if (!rel.includes("/") && ROOT_ASSET_ALLOWLIST.has(rel)) {
    precacheUrls.push("/" + rel);
  }
}

// Content-hashed filenames already change whenever their content does, so hashing that sorted
// list is a stable fingerprint of "did anything the app actually loads change" -- when it does,
// the generated sw.js's bytes change, the browser detects the update, and the new SW does a
// full precache under a fresh cache name before pruning the old one.
const version = createHash("sha256").update([...staticAssetUrls].sort().join("\n")).digest("hex").slice(0, 16);

const swSource = `// Generated by scripts/generate-sw.mjs at build time -- do not edit by hand.
const CACHE_VERSION = ${JSON.stringify(version)};
const CACHE_NAME = \`vici-sensei-\${CACHE_VERSION}\`;
const PRECACHE_URLS = ${JSON.stringify(precacheUrls)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) =>
      Promise.allSettled(
        PRECACHE_URLS.map((url) =>
          fetch(url, { cache: "no-cache" }).then((response) => {
            if (response.ok) return cache.put(url, response);
          })
        )
      )
    ).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((names) => Promise.all(names.filter((name) => name !== CACHE_NAME).map((name) => caches.delete(name))))
      .then(() => self.clients.claim())
  );
});

// Web push (lesson reminders and changes, see worker/lib/lessonsPush.ts): the Worker sends a small JSON
// message { title, body, url, tag }; the browser requires a visible notification for every push.
self.addEventListener("push", (event) => {
  let message = {};
  try {
    message = event.data ? event.data.json() : {};
  } catch {
    message = { body: event.data ? event.data.text() : "" };
  }
  event.waitUntil(
    self.registration.showNotification(message.title || "Vici Sensei", {
      body: message.body || "",
      // The same kind of notice replaces the previous one instead of piling up.
      tag: message.tag || undefined,
      icon: "/apple-icon.png",
      data: { url: message.url || "/lessons" },
    })
  );
});

// Tapping the notification opens the page: an open window of the app is reused, otherwise a new one is opened.
self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const target = new URL((event.notification.data && event.notification.data.url) || "/lessons", self.location.origin).href;
  event.waitUntil(
    self.clients.matchAll({ type: "window", includeUncontrolled: true }).then((windows) => {
      const open = windows.find((w) => "focus" in w);
      if (open) return open.focus().then(() => ("navigate" in open ? open.navigate(target) : undefined));
      return self.clients.openWindow(target);
    })
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  // Never intercept cross-origin requests -- this is what keeps Supabase (auth, data, storage)
  // completely untouched by this service worker.
  if (url.origin !== self.location.origin) return;

  // The Worker's API is same-origin in production (app.vici-sensei.com/api/*). Its answers are
  // per user and change with every write, so they must never be served from this cache: the
  // stale-while-revalidate branch below would hand back the PREVIOUS answer (one request behind
  // after every booking, and another account's answer after a log-in switch on the same browser).
  if (url.pathname.startsWith("/api/")) return;

  // Hashed build assets never change for a given URL, so once cached they're correct forever --
  // including ones deliberately left out of install-time precache (e.g. flag SVGs), which land
  // here on their first real request and get cached then instead.
  if (url.pathname.startsWith("${STATIC_ASSET_PREFIX.replace(/\/$/, "")}/")) {
    event.respondWith(
      caches.match(request).then(
        (cached) =>
          cached ||
          fetch(request).then((response) => {
            if (response.ok) caches.open(CACHE_NAME).then((cache) => cache.put(request, response.clone()));
            return response;
          })
      )
    );
    return;
  }

  // Full page loads (typed URL, reload, reopening the installed PWA): always prefer the network
  // so an online user gets the latest deploy, falling back to the precached shell when offline.
  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          return response;
        })
        .catch(() => caches.match(request).then((cached) => cached || caches.match("/")))
    );
    return;
  }

  // Everything else same-origin (icons, manifest, route prefetch payloads): serve the cached
  // copy instantly if there is one while quietly refetching in the background.
  event.respondWith(
    caches.open(CACHE_NAME).then((cache) =>
      cache.match(request).then((cached) => {
        const network = fetch(request).then((response) => {
          if (response.ok) cache.put(request, response.clone());
          return response;
        }).catch(() => cached);
        return cached || network;
      })
    )
  );
});
`;

writeFileSync(path.join(OUT_DIR, "sw.js"), swSource);
console.log(`Generated out/sw.js (${precacheUrls.length} precached URLs, cache version ${version})`);
