name: vici-sensei-local
values:
  - key: baseUrl
    value: 'http://localhost:3000'
  - key: authCookie
    value: sb-hmbemylaqnkiamvhcdcd-auth-token=PASTE_YOUR_SESSION_COOKIE_HERE
  - key: kanjiId
    value: '1'
  - key: kanjiIdNoWords
    value: '945'
  - key: kanjiIdManyWords
    value: '42'
  - key: kanjiWordId
    value: '1'
  - key: vocabId
    value: '1'
  - key: vocabIdNoKanji
    value: '158'
  - key: missingId
    value: '999999999'
  - key: sessionId
    value: ''
  - key: reviewLogId
    value: ''
  - key: custom_display_name
    value: ''
