-- Run this manually in DBeaver or the Supabase SQL editor.
--
-- Replaces the katakana reading test's word list (public.test, test_type = 'katakana') with a new
-- 113-word set chosen to cover every katakana/dakuten/handakuten/yoon/sokuon/n-combo/chōonpu/
-- extended-katakana character as directly as possible. Deleting the old rows cascades to
-- user_reading_test_progress (sentence_id references test(id) on delete cascade), but there were 0
-- progress rows for test_type='katakana' at the time of this migration, so nothing is lost.
--
-- Same conventions as 20260919_test_katakana_words.sql: no ideographic spaces in `question` (every
-- entry is a single word), particle_furiganas left null throughout (no は/を/へ grammatical-particle
-- readings in standalone loanwords).
--
-- 14 rare combinations have no everyday katakana word (they don't match common loanword-source sound
-- patterns) and are NOT covered by this list: ヂ, ヅ, ヒャ, ヒョ, ミョ, リャ, リョ, ビャ, ビョ, ピャ,
-- ピョ, トゥ, ッブ, and a standalone ヴ. The previous list (20260919) did have real, if niche/slangy,
-- words for most of these (チヂミ, ビャクダン, キョンシー, ヒョッコリ, ミョウバン, リャマ, リョウ,
-- ハッブル, ...) -- worth revisiting if full character coverage of the test is wanted; not carried
-- over here since the user asked specifically for this new word list to replace the old one as-is.

delete from public.test where test_type = 'katakana';

insert into public.test (sort_order, question, romaji, english, test_type) values
(1, 'アート', 'aato', 'art', 'katakana'),
(2, 'イースター', 'iisutaa', 'Easter', 'katakana'),
(3, 'ウール', 'uuru', 'wool', 'katakana'),
(4, 'エース', 'eesu', 'ace', 'katakana'),
(5, 'オーブン', 'oobun', 'oven', 'katakana'),
(6, 'カード', 'kaado', 'card', 'katakana'),
(7, 'スキー', 'sukii', 'ski', 'katakana'),
(8, 'クーラー', 'kuuraa', 'air conditioner', 'katakana'),
(9, 'ケーキ', 'keeki', 'cake', 'katakana'),
(10, 'コーヒー', 'koohii', 'coffee', 'katakana'),
(11, 'サービス', 'saabisu', 'service', 'katakana'),
(12, 'タクシー', 'takushii', 'taxi', 'katakana'),
(13, 'スーツ', 'suutsu', 'suit', 'katakana'),
(14, 'セーター', 'seetaa', 'sweater', 'katakana'),
(15, 'ソーセージ', 'sooseeji', 'sausage', 'katakana'),
(16, 'チーズ', 'chiizu', 'cheese', 'katakana'),
(17, 'ツール', 'tsuuru', 'tool', 'katakana'),
(18, 'テーブル', 'teeburu', 'table', 'katakana'),
(19, 'トースト', 'toosuto', 'toast', 'katakana'),
(20, 'コーナー', 'koonaa', 'corner', 'katakana'),
(21, 'ニーズ', 'niizu', 'needs / demand', 'katakana'),
(22, 'ヌードル', 'nuudoru', 'noodle', 'katakana'),
(23, 'ネーム', 'neemu', 'name', 'katakana'),
(24, 'ノート', 'nooto', 'notebook', 'katakana'),
(25, 'ハート', 'haato', 'heart', 'katakana'),
(26, 'ヘーゼルナッツ', 'heezerunattsu', 'hazelnut', 'katakana'),
(27, 'ホームページ', 'hoomupeeji', 'homepage', 'katakana'),
(28, 'ハンマー', 'hanmaa', 'hammer', 'katakana'),
(29, 'ミートボール', 'miitobooru', 'meatball', 'katakana'),
(30, 'ムード', 'muudo', 'mood', 'katakana'),
(31, 'メール', 'meeru', 'email', 'katakana'),
(32, 'モーター', 'mootaa', 'motor', 'katakana'),
(33, 'プレイヤー', 'pureiyaa', 'player', 'katakana'),
(34, 'ユーモア', 'yuumoa', 'humor', 'katakana'),
(35, 'ヨーグルト', 'yooguruto', 'yogurt', 'katakana'),
(36, 'シリーズ', 'shiriizu', 'series', 'katakana'),
(37, 'ルーム', 'ruumu', 'room', 'katakana'),
(38, 'カレー', 'karee', 'curry', 'katakana'),
(39, 'ヒーロー', 'hiiroo', 'hero', 'katakana'),
(40, 'ワード', 'waado', 'word', 'katakana'),
(41, 'ガム', 'gamu', 'gum', 'katakana'),
(42, 'ピザ', 'piza', 'pizza', 'katakana'),
(43, 'サラダ', 'sarada', 'salad', 'katakana'),
(44, 'デパート', 'depaato', 'department store', 'katakana'),
(45, 'マンゴー', 'mangoo', 'mango', 'katakana'),
(46, 'キャベツ', 'kyabetsu', 'cabbage', 'katakana'),
(47, 'キューブ', 'kyuubu', 'cube', 'katakana'),
(48, 'キョン', 'kyon', 'muntjac (deer species)', 'katakana'),
(49, 'シャワー', 'shawaa', 'shower', 'katakana'),
(50, 'シュート', 'shuuto', 'shoot (sports)', 'katakana'),
(51, 'ショップ', 'shoppu', 'shop', 'katakana'),
(52, 'チャンス', 'chansu', 'chance', 'katakana'),
(53, 'チューリップ', 'chuurippu', 'tulip', 'katakana'),
(54, 'チョコレート', 'chokoreeto', 'chocolate', 'katakana'),
(55, 'ニャー', 'nyaa', 'meow', 'katakana'),
(56, 'ニュース', 'nyuusu', 'news', 'katakana'),
(57, 'ニョッキ', 'nyokki', 'gnocchi', 'katakana'),
(58, 'ヒューズ', 'hyuuzu', 'fuse', 'katakana'),
(59, 'ミャンマー', 'myanmaa', 'Myanmar', 'katakana'),
(60, 'ミュージック', 'myuujikku', 'music', 'katakana'),
(61, 'リュックサック', 'ryukkusakku', 'rucksack / backpack', 'katakana'),
(62, 'ギャング', 'gyangu', 'gang', 'katakana'),
(63, 'レギュラー', 'regyuraa', 'regular', 'katakana'),
(64, 'ギョーザ', 'gyooza', 'dumpling', 'katakana'),
(65, 'ジャム', 'jamu', 'jam', 'katakana'),
(66, 'ジュース', 'juusu', 'juice', 'katakana'),
(67, 'ジョギング', 'jogingu', 'jogging', 'katakana'),
(68, 'インタビュー', 'intabyuu', 'interview', 'katakana'),
(69, 'コンピューター', 'konpyuutaa', 'computer', 'katakana'),
(70, 'サッカー', 'sakkaa', 'soccer', 'katakana'),
(71, 'クッキー', 'kukkii', 'cookie', 'katakana'),
(72, 'パッケージ', 'pakkeeji', 'package', 'katakana'),
(73, 'モロッコ', 'morokko', 'Morocco', 'katakana'),
(74, 'マッサージ', 'massaaji', 'massage', 'katakana'),
(75, 'ファッション', 'fasshon', 'fashion', 'katakana'),
(76, 'レッスン', 'ressun', 'lesson', 'katakana'),
(77, 'メッセージ', 'messeeji', 'message', 'katakana'),
(78, 'エスプレッソ', 'esupuresso', 'espresso', 'katakana'),
(79, 'カッター', 'kattaa', 'cutter', 'katakana'),
(80, 'サンドイッチ', 'sandoicchi', 'sandwich', 'katakana'),
(81, 'ナッツ', 'nattsu', 'nuts', 'katakana'),
(82, 'バッテリー', 'batterii', 'battery', 'katakana'),
(83, 'ロボット', 'robotto', 'robot', 'katakana'),
(84, 'ヨーロッパ', 'yooroppa', 'Europe', 'katakana'),
(85, 'ヒッピー', 'hippii', 'hippie', 'katakana'),
(86, 'ワッペン', 'wappen', 'patch / badge', 'katakana'),
(87, 'ニッポン', 'nippon', 'Japan', 'katakana'),
(88, 'バッグ', 'baggu', 'bag', 'katakana'),
(89, 'グッズ', 'guzzu', 'goods', 'katakana'),
(90, 'ベッド', 'beddo', 'bed', 'katakana'),
(91, 'バッジ', 'bajji', 'badge', 'katakana'),
(92, 'アンナ', 'anna', 'Anna (name)', 'katakana'),
(93, 'アンニュイ', 'annyui', 'languid / ennui', 'katakana'),
(94, 'アンヌ', 'annu', 'Anne (name)', 'katakana'),
(95, 'アンネ', 'anne', 'Anne (e.g. Anne Frank)', 'katakana'),
(96, 'アンノウン', 'announ', 'unknown', 'katakana'),
(97, 'ヴァイオリン', 'vaiorin', 'violin', 'katakana'),
(98, 'ヴィーガン', 'viigan', 'vegan', 'katakana'),
(99, 'ヴェール', 'veeru', 'veil', 'katakana'),
(100, 'ヴォーカル', 'vookaru', 'vocal', 'katakana'),
(101, 'シェフ', 'shefu', 'chef', 'katakana'),
(102, 'ジェットコースター', 'jettokoosutaa', 'roller coaster', 'katakana'),
(103, 'チェック', 'chekku', 'check', 'katakana'),
(104, 'パーティー', 'paatii', 'party', 'katakana'),
(105, 'キャンディ', 'kyandi', 'candy', 'katakana'),
(106, 'ヒンドゥー', 'hinduu', 'Hindu', 'katakana'),
(107, 'ファミリー', 'famirii', 'family', 'katakana'),
(108, 'フィルム', 'firumu', 'film', 'katakana'),
(109, 'カフェ', 'kafe', 'café', 'katakana'),
(110, 'フォーク', 'fooku', 'fork', 'katakana'),
(111, 'ウィンドウ', 'windou', 'window', 'katakana'),
(112, 'ウェブ', 'webu', 'web', 'katakana'),
(113, 'ウォーキング', 'wookingu', 'walking', 'katakana');
