-- Run this manually in DBeaver or the Supabase SQL editor.
--
-- Adds the katakana reading test: 100 loanwords/single-word entries in public.test (renamed from
-- reading_test_sentences -- see 20260918_rename_reading_test_sentences_to_test.sql, which already
-- widened the test_type check constraint to allow 'katakana'), mirroring the word-based hiragana
-- test's shape (20260903_reading_test_hiragana_words.sql).
--
-- No ideographic spaces (U+3000) in `question` here, unlike the hiragana test's spacing (see
-- 20260902_reading_test_hiragana_spacing.sql / 20260903_reading_test_hiragana_words_spacing.sql):
-- that rule follows the `romaji` column's own word boundaries, and every one of these 100 romaji
-- values is a single word with no internal space -- including pyonpyon (row 97), even though its
-- hiragana counterpart (ぴょんぴょん, "pyon pyon") was spaced, because the source word list gives
-- it as one romaji word here, not two.
--
-- particle_furiganas is left null throughout -- these are standalone loanwords, not sentences, so
-- は/を/へ never appear as a grammatical particle needing a reading hint.

insert into public.test (sort_order, question, romaji, english, test_type) values
(1, 'マンニトール', 'mannitooru', 'mannitol', 'katakana'),
(2, 'サンドウィッチ', 'sandouicchi', 'sandwich', 'katakana'),
(3, 'ヘーゼルナッツ', 'heezerunattsu', 'hazelnut', 'katakana'),
(4, 'キャッシュ', 'kyasshu', 'cash', 'katakana'),
(5, 'レギュラー', 'regyuraa', 'regular', 'katakana'),
(6, 'ソーセージ', 'sooseeji', 'sausage', 'katakana'),
(7, 'ヨーロッパ', 'yooroppa', 'Europe', 'katakana'),
(8, 'ミーティング', 'miitingu', 'meeting', 'katakana'),
(9, 'コンピューター', 'konpyuutaa', 'computer', 'katakana'),
(10, 'メーカー', 'meekaa', 'maker / brand', 'katakana'),
(11, 'ヒャッホー', 'hyahhoo', 'yahoo! (exclamation of joy)', 'katakana'),
(12, 'ケチャップ', 'kechappu', 'ketchup', 'katakana'),
(13, 'ボンネット', 'bonnetto', 'car bonnet / hood', 'katakana'),
(14, 'ディズニー', 'dizunii', 'Disney', 'katakana'),
(15, 'ビュッフェ', 'byuffe', 'buffet', 'katakana'),
(16, 'ハーブ', 'haabu', 'herb', 'katakana'),
(17, 'ユーザー', 'yuuzaa', 'user', 'katakana'),
(18, 'シャワー', 'shawaa', 'shower', 'katakana'),
(19, 'ヴァイオリン', 'vaiorin', 'violin', 'katakana'),
(20, 'エアー', 'eaa', 'air', 'katakana'),
(21, 'ヤッケ', 'yakke', 'anorak', 'katakana'),
(22, 'バッジ', 'bajji', 'badge', 'katakana'),
(23, 'カヌー', 'kanuu', 'canoe', 'katakana'),
(24, 'ベッド', 'beddo', 'bed', 'katakana'),
(25, 'アッペ', 'appe', 'appendicitis (slang)', 'katakana'),
(26, 'ノート', 'nooto', 'notebook', 'katakana'),
(27, 'ウォッカ', 'wokka', 'vodka', 'katakana'),
(28, 'ニョッキ', 'nyokki', 'gnocchi', 'katakana'),
(29, 'チェック', 'chekku', 'check', 'katakana'),
(30, 'モーター', 'mootaa', 'motor', 'katakana'),
(31, 'コーヒー', 'koohii', 'coffee', 'katakana'),
(32, 'ニッポン', 'nippon', 'Japan', 'katakana'),
(33, 'ビャクダン', 'byakudan', 'sandalwood', 'katakana'),
(34, 'キョンシー', 'kyonshii', 'jiangshi (Chinese hopping vampire)', 'katakana'),
(35, 'ヒョッコリ', 'hyokkori', 'suddenly / unexpectedly (onomatopoeia)', 'katakana'),
(36, 'カンガルー', 'kangaruu', 'kangaroo', 'katakana'),
(37, 'ミャンマー', 'myanmaa', 'Myanmar', 'katakana'),
(38, 'サーフィン', 'saafin', 'surfing', 'katakana'),
(39, 'チョコレート', 'chokoreeto', 'chocolate', 'katakana'),
(40, 'ショッピング', 'shoppingu', 'shopping', 'katakana'),
(41, 'マネージャー', 'maneejaa', 'manager', 'katakana'),
(42, 'エッグ', 'eggu', 'egg', 'katakana'),
(43, 'アンヌ', 'annu', 'Anne', 'katakana'),
(44, 'ゴール', 'gooru', 'goal', 'katakana'),
(45, 'フード', 'fuudo', 'food / hood', 'katakana'),
(46, 'ケーキ', 'keeki', 'cake', 'katakana'),
(47, 'チヂミ', 'chijimi', 'chijimi (Korean pancake)', 'katakana'),
(48, 'ゾンビ', 'zonbi', 'zombie', 'katakana'),
(49, 'ピャー', 'pyaa', 'eek! (surprise sound effect)', 'katakana'),
(50, 'アンナ', 'anna', 'Anna', 'katakana'),
(51, 'ムード', 'muudo', 'mood', 'katakana'),
(52, 'チーズ', 'chiizu', 'cheese', 'katakana'),
(53, 'リャマ', 'ryama', 'llama', 'katakana'),
(54, 'ギャル', 'gyaru', 'gal', 'katakana'),
(55, 'クール', 'kuuru', 'cool', 'katakana'),
(56, 'ロープ', 'roopu', 'rope', 'katakana'),
(57, 'ソファ', 'sofa', 'sofa', 'katakana'),
(58, 'グッズ', 'guzzu', 'goods / merch', 'katakana'),
(59, 'ウール', 'uuru', 'wool', 'katakana'),
(60, 'シェア', 'shea', 'share', 'katakana'),
(61, 'リョウ', 'ryou', 'Ryo (name)', 'katakana'),
(62, 'エース', 'eesu', 'ace', 'katakana'),
(63, 'ゲーム', 'geemu', 'game', 'katakana'),
(64, 'ハッブル', 'habburu', 'Hubble', 'katakana'),
(65, 'ジュース', 'juusu', 'juice', 'katakana'),
(66, 'フォーク', 'fooku', 'fork', 'katakana'),
(67, 'ニュース', 'nyuusu', 'news', 'katakana'),
(68, 'ギョーザ', 'gyooza', 'gyoza', 'katakana'),
(69, 'キューバ', 'kyuuba', 'Cuba', 'katakana'),
(70, 'テーブル', 'teeburu', 'table', 'katakana'),
(71, 'ジョーク', 'jooku', 'joke', 'katakana'),
(72, 'ジェット', 'jetto', 'jet', 'katakana'),
(73, 'ハッスル', 'hassuru', 'hustle', 'katakana'),
(74, 'ビョーキ', 'byouki', 'sick (slang)', 'katakana'),
(75, 'イーグル', 'iiguru', 'eagle', 'katakana'),
(76, 'クッキー', 'kukkii', 'cookie', 'katakana'),
(77, 'コーナー', 'koonaa', 'corner', 'katakana'),
(78, 'ニャンコ', 'nyanko', 'kitty', 'katakana'),
(79, 'スーパー', 'suupaa', 'super / supermarket', 'katakana'),
(80, 'リュック', 'ryukku', 'backpack', 'katakana'),
(81, 'エッセイ', 'essei', 'essay', 'katakana'),
(82, 'ヴェール', 'veeru', 'veil', 'katakana'),
(83, 'オーブン', 'oobun', 'oven', 'katakana'),
(84, 'マッタリ', 'mattari', 'chill / relaxed (slang)', 'katakana'),
(85, 'アッサリ', 'assari', 'light / plain (taste)', 'katakana'),
(86, 'バッテリー', 'batterii', 'battery', 'katakana'),
(87, 'ミョウバン', 'myouban', 'alum', 'katakana'),
(88, 'チュニジア', 'chunijia', 'Tunisia', 'katakana'),
(89, 'アンノウン', 'announ', 'unknown', 'katakana'),
(90, 'イヤーカフ', 'iyaakafu', 'ear cuff', 'katakana'),
(91, 'ウェイター', 'weitaa', 'waiter', 'katakana'),
(92, 'ヒューマン', 'hyuuman', 'human', 'katakana'),
(93, 'ヴードゥー', 'vuuduu', 'voodoo', 'katakana'),
(94, 'ツーリング', 'tsuuringu', 'touring', 'katakana'),
(95, 'ヴォーカル', 'vookaru', 'vocal', 'katakana'),
(96, 'ヴィーナス', 'viinasu', 'Venus', 'katakana'),
(97, 'ピョンピョン', 'pyonpyon', 'hop hop (hopping onomatopoeia)', 'katakana'),
(98, 'エスプレッソ', 'esupuresso', 'espresso', 'katakana'),
(99, 'トゥクトゥク', 'tukutuku', 'tuk-tuk', 'katakana'),
(100, 'ミュージック', 'myuujikku', 'music', 'katakana');
